MuserUI/Models/Sync/AuthorizeForm.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class AuthorizeForm
    {
        public string Login { get; set; }
        public string Pass { get; set; }
    }
}

MuserUI/Models/Sync/AuthorizeResult.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class AuthorizeResult
    {
        public bool Success { get; set; }
    }
}

MuserUI/Models/Sync/ExternalInputTracksModel.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class ExternalInputTracksModel
    {
        public string Text { get; set; }
    }
}

MuserUI/Models/Sync/InputTracksModel.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class InputTracksModel
    {
        public string Text { get; set; }
    }
}

MuserUI/Models/Sync/ProgressModel.cs
using System;
using System.Collections.Generic;

namespace Tolltech.MuserUI.Models.Sync
{
    public class ProgressModel
    {
        public ProgressModel()
        {
            Errors = new List<(TrackModel Track, string Message)>();
        }

        public Guid Id { get; set; }
        public Guid? SessionId { get; set; }
        public int Total { get; set; }
        public int Processed { get; set; }
        public bool ImportLogsSaved { get; set; }
        public List<(TrackModel Track, string Message)> Errors { get; set; }
    }
}

MuserUI/Models/Sync/TrackImportForm.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class TrackImportForm
    {
        public TracksModel Tracks { get; set; }
        public string YaPlaylistId { get; set; }
    }
}

MuserUI/Models/Sync/TrackModel.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class TrackModel
    {
        public string Artist { get; set; }
        public string Title { get; set; }
    }
}

MuserUI/Models/Sync/TracksModel.cs
using System.Collections.Generic;

namespace Tolltech.MuserUI.Models.Sync
{
    public class TracksModel
    {
        public TracksModel()
        {
            Tracks = new List<TrackModel>();
        }

        public List<TrackModel> Tracks { get; set; }
    }
}

MuserUI/Models/Sync/TracksWizardModel.cs
using System;

namespace Tolltech.MuserUI.Models.Sync
{
    public class TracksWizardModel
    {
        public TracksWizardModel()
        {
            Tracks = Array.Empty<TrackModel>();
        }

        public TrackModel[] Tracks { get; set; }
    }
}

MuserUI/Models/Sync/YaPlaylist.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class YaPlaylist
    {
        public string Title { get; set; }
        public string Id { get; set; }
    }
}

MuserUI/Models/Sync/YaPlaylists.cs
using System;

namespace Tolltech.MuserUI.Models.Sync
{
    public class YaPlaylists
    {
        public YaPlaylists()
        {
            Playlists = Array.Empty<YaPlaylist>();
        }

        public YaPlaylist[] Playlists { get; set; }
    }
}

MuserUI/Models/SyncWizard/YaPlaylistsForm.cs
using System;
using Tolltech.MuserUI.Models.Sync;

namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class YaPlaylistsForm
    {
        public YaPlaylistsForm()
        {
            Playlists = Array.Empty<YaPlaylist>();
        }

        public YaPlaylist[] Playlists { get; set; }
        public string SelectedPlaylistId { get; set; }
        public string Login { get; set; }
    }}

MuserUI/Controllers/SyncController.cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Tolltech.Muser.Domain;
using Tolltech.Muser.Models;
using Tolltech.Muser.Settings;
using Tolltech.MuserUI.Common;
using Tolltech.MuserUI.Extensions;
using Tolltech.MuserUI.Models.Sync;
using Tolltech.MuserUI.Sync;
using Tolltech.SqlEF;

namespace Tolltech.MuserUI.Controllers
{
    [Authorize]
    [Route("oldsync")]
    public class SyncController : BaseController
    {
        private readonly IImportResultLogger importResultLogger;
        private readonly IQueryExecutorFactory queryExecutorFactory;
        private readonly ITempSessionService tempSessionService;

        private readonly IYandexService yandexService;
        private readonly IAuthorizationSettings authorizationSettings;
        private readonly IDomainService domainService;
        private readonly ITrackGetter trackGetter;
        private readonly IProgressBar progressBar;

        public SyncController(IYandexService yandexService, IAuthorizationSettings authorizationSettings,
            IDomainService domainService, ITrackGetter trackGetter, IProgressBar progressBar,
            IImportResultLogger importResultLogger, IQueryExecutorFactory queryExecutorFactory,
            ITempSessionService tempSessionService
        )
        {
            this.yandexService = yandexService;
            this.authorizationSettings = authorizationSettings;
            this.domainService = domainService;
            this.trackGetter = trackGetter;
            this.progressBar = progressBar;
            this.importResultLogger = importResultLogger;
            this.queryExecutorFactory = queryExecutorFactory;
            this.tempSessionService = tempSessionService;
        }

        [HttpGet("")]
        public async Task<ActionResult> Index(Guid? sessionId)
        {
            if (!sessionId.HasValue)
            {
                return View();
            }

            var tracksText = await tempSessionService.FindSessionTextAsync(sessionId.Value, UserId).ConfigureAwait(true);

            if (tracksText?.IsNullOrWhitespace() ?? true)
            {
                return View();
            }

            var sourceTracks = trackGetter.GetTracks(tracksText);
            return View(sourceTracks.ToTracksModel());
        }

        [HttpGet("yatracks")]
        public async Task<ActionResult> GetYaTracks(string yaPlaylistId)
        {
            var client = await yandexService.GetClientAsync(UserId).ConfigureAwait(true);

            var tracks = await client.GetTracksAsync(yaPlaylistId).ConfigureAwait(true);

            return PartialView("Tracks", tracks.ToTracksModel());
        }

        [HttpPost("unauthorizeya")]
        public void UnauthorizeYa()
        {
            var authInfo = authorizationSettings.GetCachedMuserAuthorization(UserId);
            if (authInfo == null)
            {
                return;
            }
            else
            {
                authInfo.YaLogin = string.Empty;
                authInfo.YaPassword = string.Empty;
            }

            authorizationSettings.SetMuserAuthorization(authInfo, UserId);
        }

        [HttpPost("authorizeya")]
        public async Task<ActionResult> AuthorizeYa(AuthorizeForm authorizeForm)
        {
            var success = await yandexService.CheckCredentialsAsync(authorizeForm.Login, authorizeForm.Pass)
                .ConfigureAwait(true);

            Response.SetCookies(Constants.YaLoginCookie, authorizeForm.Login ?? string.Empty);

            if (!success)
            {
                return PartialView("AuthorizeResult", new AuthorizeResult {Success = false});
            }

            var authInfo = authorizationSettings.GetCachedMuserAuthorization(UserId);
            if (authInfo == null)
            {
                authInfo = new MuserAuthorization
                {
                    YaLogin = authorizeForm.Login,
                    YaPassword = authorizeForm.Pass
                };
            }
            else
            {
                authInfo.YaLogin = authorizeForm.Login;
                authInfo.YaPassword = authorizeForm.Pass;
            }

            authorizationSettings.SetMuserAuthorization(authInfo, UserId);

            return await GetYaPlaylists().ConfigureAwait(true);
        }

        [HttpGet("yaplaylists")]
        public async Task<ActionResult> GetYaPlaylists()
        {
            var client = await yandexService.GetClientAsync(UserId).ConfigureAwait(true);

            var playlists = await client.GetPlaylistsAsync().ConfigureAwait(true);

            return PartialView("YaPlaylists", new YaPlaylists
            {
                Playlists = playlists
                    .Select(x => new YaPlaylist
                    {
                        Title = x.Title,
                        Id = x.Id
                    })
                    .ToArray()
            });
        }

        [HttpPost("inputtracksexternal")]
        [AllowAnonymous]
        [EnableCors(Constants.MuserCorsPolicy)]
        public async Task<JsonResult> GetInputTracksExternal([FromBody] ExternalInputTracksModel inputTracks)
        {
            var sessionId = Guid.NewGuid();

            await tempSessionService.SaveTempSessionAsync(sessionId, SafeUserId, inputTracks?.Text ?? string.Empty).ConfigureAwait(true);
            
            var url = Url.Action("Index", new {sessionId = sessionId});
            return Json(new {Url = url});
        }

        [HttpPost("inputtracks")]
        public ActionResult GetInputTracks(InputTracksModel inputTracks)
        {
            var sourceTracks = trackGetter.GetTracks(inputTracks.Text);
            return PartialView("Tracks", sourceTracks.ToTracksModel());
        }

        [HttpPost("inputtracksfromfile")]
        public async Task<ActionResult> GetInputTracksFromFile(IFormFile uploadedFile)
        {
            await using var memoryStream = new MemoryStream();
            await uploadedFile.CopyToAsync(memoryStream).ConfigureAwait(true);

            var fileBody = Encoding.UTF8.GetString(memoryStream.ToArray());

            var playlist = new PlaylistDbo
            {
                Id = Guid.NewGuid(),
                Content = fileBody,
                Date = DateTime.Now,
                UserId = UserId,
                Filename = uploadedFile.FileName,
                Extension = new string(uploadedFile.FileName?.Reverse().TakeWhile(c => c != '.').Reverse().ToArray() ??
                                       Array.Empty<char>())
            };
            using var queryExecutor = queryExecutorFactory.Create<PlaylistsHandler, PlaylistDbo>();
            await queryExecutor.ExecuteAsync(f => f.CreateAsync(playlist)).ConfigureAwait(true);

            var sourceTracks = trackGetter.GetTracks(fileBody);
            return PartialView("Tracks", sourceTracks.ToTracksModel());
        }

        [HttpPost("newtracks")]
        public async Task<ActionResult> GetNewTracks()
        {
            var tracksForm = await GetFromBodyAsync<TrackImportForm>().ConfigureAwait(true);
            var inputTracks = tracksForm.Tracks.ToTracksModel();
            var tracks = await domainService.GetNewTracksAsync(tracksForm.YaPlaylistId, UserId, inputTracks)
                .ConfigureAwait(true);
            return PartialView("Tracks", tracks.ToTracksModel());
        }

        [HttpPost("import")]
        public async Task<ActionResult> ImportTracks([FromBody] TrackImportForm tracksForm)
        {
            var trackToImport = tracksForm.Tracks.Tracks
                .Select(x => new NormalizedTrack
                {
                    Artist = x.Artist,
                    Title = x.Title,
                })
                .Reverse()
                .ToArray();

            var progressId = Guid.NewGuid();

            var results = await domainService.ImportTracksAsync(trackToImport, tracksForm.YaPlaylistId, UserId, tuple =>
                progressBar.UpdateProgressModel(new ProgressModel
                {
                    Id = progressId,
                    Processed = tuple.Processed,
                    Total = tuple.Total,
                })).ConfigureAwait(true);

            await importResultLogger.WriteImportLogsAsync(results, UserId, null).ConfigureAwait(true);

            return PartialView("Progress", progressBar.FindProgressModel(progressId));
        }
    }
}

MuserUI/Views/Sync/AuthorizeResult.cshtml
@model Tolltech.MuserUI.Models.Sync.AuthorizeResult

@if (!Model.Success)
{
    <label style="color: red">Ошибка авторизации</label>
}
else
{
    <label>Ok!</label>
}

MuserUI/Views/Sync/Index.cshtml
@using Tolltech.MuserUI.Common
@using Tolltech.MuserUI.Extensions
@using Tolltech.MuserUI.Models.Sync
@{
    ViewBag.Title = "Tollmuser";
}

@model TracksModel
<table>
    <tr>
        <td>
            <div id="inputPlayLists">
                @await Html.PartialAsync("InputTracks", new InputTracksModel())
            </div>
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            @await Html.PartialAsync("YaAuthorize", new AuthorizeForm {Login = Context.Request.FindCookies(Constants.YaLoginCookie) ?? string.Empty})
        </td>
    </tr>
    <tr>
        <td>
            <div>
                @await Html.PartialAsync("InputPlaylistFile")
            </div>
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <div id="yaPlaylists">
                @await Html.PartialAsync("YaPlaylists", new YaPlaylists())
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div id="inputTracks">
                @await Html.PartialAsync("Tracks", Model ?? new TracksModel())
            </div>
        </td>
        <td></td>
        <td>
            <div>
                <input id="syncButton" type="button" value="Показать новые треки" disabled="disabled" class="importButtons"/>
                <input id="importButton" type="button" value="Импорт" disabled="disabled" class="importButtons"/>
            </div>
        </td>
        <td></td>
        <td>
            <div id="yaTracks">
                @await Html.PartialAsync("Tracks", new TracksModel())
            </div>
        </td>
    </tr>
</table>

@section Scripts{
    <script type="text/javascript">
        SyncControl('@Url.Action("GetNewTracks", "Sync")','@Url.Action("ImportTracks", "Sync")');
    </script>
}

MuserUI/Views/Sync/InputPlaylistFile.cshtml
<form asp-action="GetInputTracksFromFile" asp-controller="Sync" method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile"/><br>
    <input type="submit" value="Загрузить" class="btn btn-outline-dark"/>
</form>

MuserUI/Views/Sync/InputTracks.cshtml
@model Tolltech.MuserUI.Models.Sync.InputTracksModel
<form id="tracksInputForm" asp-action="GetInputTracks" asp-controller="Sync"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-mode="replace"
      data-ajax-success="InputSuccess(data)"
      data-ajax-failure="InputFail()"
      data-ajax-update="#inputTracks">
    <div>
        @Html.TextAreaFor(x => x.Text, new {id = "inputAudioStr", style = "width:100%"})
    </div>
    <input type="submit" value="Распарсить треки" class="btn btn-outline-dark"/>
</form>

MuserUI/Views/Sync/Tracks.cshtml
@model Tolltech.MuserUI.Models.Sync.TracksModel
<div>
    @Html.ListBoxFor(x => x.Tracks, Model.Tracks.Select(x => new SelectListItem
    {
        Text = x.Artist + " - " + x.Title,
        Value = Json.Serialize(x).ToString()
    }), new{style= "max-width:500px;min-width:300px;height:500px;line-height:500px;" })
</div>

MuserUI/Views/Sync/YaAuthorize.cshtml
@model Tolltech.MuserUI.Models.Sync.AuthorizeForm

<form asp-action="AuthorizeYa" asp-controller="Sync"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-mode="replace"
      data-ajax-success="$('#yaPlaylistForm').submit()"
      data-ajax-failure="YaFail()"
      data-ajax-update="#yaPlaylists">

    <fieldset>
        <legend>Авторизация Яндекс</legend>
        <div>
            @Html.LabelFor(m => m.Login, "Логин")
            @Html.TextBoxFor(m => m.Login)
        </div>
        <div>
            @Html.LabelFor(m => m.Pass, "Пароль")
            @Html.PasswordFor(m => m.Pass)
        </div>
        <input type="submit" value="Авторизовать" class="btn btn-outline-dark"/>
        <input type="button" value="Разлогиниться" id="unAuthorizeButton" onclick='UnauthorizeYa("@Url.Action("UnauthorizeYa", "Sync")")' class="btn btn-outline-dark"/>
    </fieldset>
</form>

MuserUI/Views/Sync/YaPlaylists.cshtml
@model Tolltech.MuserUI.Models.Sync.YaPlaylists
<form id="yaPlaylistForm" asp-action="GetYaTracks" asp-controller="Sync"
      data-ajax="true"
      data-ajax-method="GET"
      data-ajax-mode="replace"
      data-ajax-success="YaSuccess(data)"
      data-ajax-failure="YaFail()"
      data-ajax-update="#yaTracks">
    @Html.DropDownList("yaPlaylistId", Model.Playlists.Select(x => new SelectListItem {Value = x.Id, Text = x.Title, Selected = x.Title == "Vk"}), new {id = "yaPlaylists"})
</form>