MuserUI/Models/Sync/YaPlaylist.cs
namespace Tolltech.MuserUI.Models.Sync
{
    public class YaPlaylist
    {
        public string Title { get; set; }
        public string Id { get; set; }
    }
}

MuserUI/Models/Sync/YaPlaylists.cs
using System;

namespace Tolltech.MuserUI.Models.Sync
{
    public class YaPlaylists
    {
        public YaPlaylists()
        {
            Playlists = Array.Empty<YaPlaylist>();
        }

        public YaPlaylist[] Playlists { get; set; }
    }
}

MuserUI/Models/SyncWizard/InputTracksSessionForm.cs
namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class InputTracksSessionForm
    {
        public string TracksJson { get; set; }
    }
}

MuserUI/Models/SyncWizard/ProgressWithUrlModel.cs
using System;
using Tolltech.MuserUI.Models.Sync;

namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class ProgressWithUrlModel
    {
        public ProgressModel Progress { get; set; }
        public string YandexPlaylistUrl { get; set; }
        public Guid SessionId { get; set; }
    }
}

MuserUI/Models/SyncWizard/ReImportForm.cs
using System;

namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class ReImportForm
    {
        public ReImportForm()
        {
            Tracks = Array.Empty<ReImportTrackForm>();
        }

        public Guid SessionId { get; set; }
        public ReImportTrackForm[] Tracks { get; set; }
        public string PlaylistId { get; set; }
    }
}

MuserUI/Models/SyncWizard/ReImportFormJson.cs
namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class ReImportFormJson
    {
        public string ReImportForm { get; set; }
    }
}

MuserUI/Models/SyncWizard/ReImportModel.cs
using System;

namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class ReImportModel
    {
        public ReImportModel()
        {
            Tracks = Array.Empty<ReImportTrack>();
        }

        public ReImportTrack[] Tracks { get; set; }
        public Guid SessionId { get; set; }
        public string PlaylistId { get; set; }
        public string PlaylistUrl { get; set; }
        public int Total { get; set; }
        public int Success { get; set; }
    }
}

MuserUI/Models/SyncWizard/ReImportTrack.cs
using System;

namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class ReImportTrack
    {
        public string InputTitle { get; set; }
        public string InputArtist { get; set; }
        public string TrackId { get; set; }
        public string AlbumId { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public bool Selected { get; set; }
        public Guid Id { get; set; }
        public bool Disabled { get; set; }
    }
}

MuserUI/Models/SyncWizard/ReImportTrackForm.cs
using System;

namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class ReImportTrackForm
    {
        public string AlbumId { get; set; }
        public string TrackId { get; set; }
        public Guid Id { get; set; }
    }
}

MuserUI/Models/SyncWizard/YaPlaylistsForm.cs
using System;
using Tolltech.MuserUI.Models.Sync;

namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class YaPlaylistsForm
    {
        public YaPlaylistsForm()
        {
            Playlists = Array.Empty<YaPlaylist>();
        }

        public YaPlaylist[] Playlists { get; set; }
        public string SelectedPlaylistId { get; set; }
        public string Login { get; set; }
    }}

MuserUI/Models/SyncWizard/YandexAuthorizeForm.cs
namespace Tolltech.MuserUI.Models.SyncWizard
{
    public class YandexAuthorizeForm
    {
        public string Login { get; set; }
        public string Pass { get; set; }
        public bool AuthFailed { get; set; }
        public bool Forbid { get; set; }
    }
}

MuserUI/Controllers/SyncWizardController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Tolltech.Muser.Domain;
using Tolltech.Muser.Models;
using Tolltech.Muser.Settings;
using Tolltech.MuserUI.Common;
using Tolltech.MuserUI.Extensions;
using Tolltech.MuserUI.Models.Sync;
using Tolltech.MuserUI.Models.SyncWizard;
using Tolltech.MuserUI.Sync;
using Tolltech.Serialization;
using Tolltech.SqlEF;
using Tolltech.YandexClient.ApiModels;

namespace Tolltech.MuserUI.Controllers
{
    [Authorize]
    [Route("sync")]
    public class SyncWizardController : BaseController
    {
        private readonly ITempSessionService tempSessionService;
        private readonly ITrackGetter trackGetter;
        private readonly IQueryExecutorFactory queryExecutorFactory;
        private readonly IYandexService yandexService;
        private readonly IAuthorizationSettings authorizationSettings;
        private readonly IJsonSerializer jsonSerializer;
        private readonly IJsonTrackGetter jsonTrackGetter;
        private readonly IDomainService domainService;
        private readonly IProgressBar progressBar;
        private readonly IImportResultLogger importResultLogger;
        private readonly ICaptcha captcha;

        public SyncWizardController(ITempSessionService tempSessionService, ITrackGetter trackGetter,
            IQueryExecutorFactory queryExecutorFactory,
            IYandexService yandexService, IAuthorizationSettings authorizationSettings,
            IJsonSerializer jsonSerializer,
            IJsonTrackGetter jsonTrackGetter,
            IDomainService domainService,
            IProgressBar progressBar,
            IImportResultLogger importResultLogger,
            ICaptcha captcha)
        {
            this.tempSessionService = tempSessionService;
            this.trackGetter = trackGetter;
            this.queryExecutorFactory = queryExecutorFactory;
            this.yandexService = yandexService;
            this.authorizationSettings = authorizationSettings;
            this.jsonSerializer = jsonSerializer;
            this.jsonTrackGetter = jsonTrackGetter;
            this.domainService = domainService;
            this.progressBar = progressBar;
            this.importResultLogger = importResultLogger;
            this.captcha = captcha;
        }

        [HttpGet("")]
        public async Task<ActionResult> Index(Guid? sessionId)
        {
            if (!sessionId.HasValue)
            {
                return View();
            }

            var tracksText =
                await tempSessionService.FindSessionTextAsync(sessionId.Value, UserId).ConfigureAwait(true);

            if (tracksText?.IsNullOrWhitespace() ?? true)
            {
                return View();
            }

            var sourceTracks = trackGetter.GetTracks(tracksText);
            return View("InputTracks", sourceTracks.ToTracksWizardModel());
        }

        [HttpPost("inputtracksexternal")]
        [AllowAnonymous]
        [EnableCors(Constants.MuserCorsPolicy)]
        public async Task<JsonResult> GetInputTracksExternal([FromBody] ExternalInputTracksModel inputTracks)
        {
            var sessionId = Guid.NewGuid();

            await tempSessionService.SaveTempSessionAsync(sessionId, SafeUserId, inputTracks?.Text ?? string.Empty)
                .ConfigureAwait(true);

            var url = Url.Action("Index", new {sessionId = sessionId});
            return Json(new {Url = url});
        }

        [HttpPost("inputtracks")]
        public ActionResult GetInputTracks(InputTracksModel inputTracks)
        {
            var sourceTracks = trackGetter.GetTracks(inputTracks.Text);
            return View("InputTracks", sourceTracks.ToTracksWizardModel());
        }

        [HttpPost("inputtracksfromfile")]
        public async Task<ActionResult> GetInputTracksFromFile(IFormFile uploadedFile)
        {
            await using var memoryStream = new MemoryStream();
            await uploadedFile.CopyToAsync(memoryStream).ConfigureAwait(true);

            var fileBody = Encoding.UTF8.GetString(memoryStream.ToArray());

            var playlist = new PlaylistDbo
            {
                Id = Guid.NewGuid(),
                Content = fileBody,
                Date = DateTime.Now,
                UserId = UserId,
                Filename = uploadedFile.FileName,
                Extension = new string(uploadedFile.FileName?.Reverse().TakeWhile(c => c != '.').Reverse().ToArray() ??
                                       Array.Empty<char>())
            };
            using var queryExecutor = queryExecutorFactory.Create<PlaylistsHandler, PlaylistDbo>();
            await queryExecutor.ExecuteAsync(f => f.CreateAsync(playlist)).ConfigureAwait(true);

            var sourceTracks = trackGetter.GetTracks(fileBody);
            return View("InputTracks", sourceTracks.ToTracksWizardModel());
        }

        [HttpPost("savetracks")]
        public async Task<ActionResult> SaveTracks(InputTracksSessionForm tracksSessionForm)
        {
            var tracksModel = jsonSerializer.DeserializeFromString<TracksWizardModel>(tracksSessionForm.TracksJson);
            var sourceTracks = tracksModel.ToTracksWizardModel();
            var text = jsonTrackGetter.SerializeTracks(sourceTracks);

            var sessionId = Guid.NewGuid();
            await tempSessionService.SaveTempSessionAsync(sessionId, SafeUserId, text).ConfigureAwait(true);

            if (authorizationSettings.UserAuthorized(UserId))
            {
                return RedirectToAction("GetYaPlaylists", new {sessionId = sessionId});
            }

            return RedirectToAction("YandexAuthorize", new {sessionId = sessionId});
        }

        [HttpGet("yaauthorize")]
        public ActionResult YandexAuthorize(Guid sessionId)
        {
            var yandexCookie = Request.FindCookies(Constants.YaLoginCookie);
            return View(new YandexAuthorizeForm
            {
                Login = yandexCookie
            });
        }

        [HttpPost("yaauthorize")]
        public async Task<ActionResult> YandexAuthorize(YandexAuthorizeForm authorizeForm, Guid sessionId)
        {
            if (captcha.IsForbid(UserId, "Yandex"))
            {
                return View("YandexAuthorize", new YandexAuthorizeForm {Login = authorizeForm.Login, Forbid = true});
            }

            var success = await yandexService.CheckCredentialsAsync(authorizeForm.Login, authorizeForm.Pass)
                .ConfigureAwait(true);

            Response.SetCookies(Constants.YaLoginCookie, authorizeForm.Login ?? string.Empty);

            if (!success)
            {
                captcha.IncrementForbid(UserId, "Yandex");
                return View("YandexAuthorize",
                    new YandexAuthorizeForm {Login = authorizeForm.Login, AuthFailed = true});
            }

            var authInfo = authorizationSettings.GetCachedMuserAuthorization(UserId);
            if (authInfo == null)
            {
                authInfo = new MuserAuthorization
                {
                    YaLogin = authorizeForm.Login,
                    YaPassword = authorizeForm.Pass
                };
            }
            else
            {
                authInfo.YaLogin = authorizeForm.Login;
                authInfo.YaPassword = authorizeForm.Pass;
            }

            authorizationSettings.SetMuserAuthorization(authInfo, UserId);

            return await GetYaPlaylists(sessionId).ConfigureAwait(true);
        }

        [HttpGet("yaplaylists")]
        public async Task<ActionResult> GetYaPlaylists(Guid sessionId)
        {
            var client = await yandexService.GetClientAsync(UserId).ConfigureAwait(true);

            var playlists = await client.GetPlaylistsAsync().ConfigureAwait(true);

            return View("YaPlaylists", new YaPlaylistsForm
            {
                Playlists = playlists
                    .Select(x => new YaPlaylist
                    {
                        Title = x.Title,
                        Id = x.Id
                    })
                    .ToArray(),
                SelectedPlaylistId = playlists.FirstOrDefault(x => x.Title.ToLower() == "vk")?.Id,
                Login = client.Login
            });
        }

        [HttpPost("import")]
        public async Task<ActionResult> ImportTracks(YaPlaylistsForm yaPlaylists, Guid sessionId)
        {
            var yaPlayListId = yaPlaylists.SelectedPlaylistId;

            if (yaPlayListId.IsNullOrWhitespace())
            {
                return RedirectToAction("GetYaPlaylists", new {sessionId = sessionId});
            }

            var tracksText = await tempSessionService.FindSessionTextAsync(sessionId, UserId).ConfigureAwait(true);
            var sourceTracks = trackGetter.GetTracks(tracksText);

            var trackToImport = sourceTracks
                .Select(x => new NormalizedTrack
                {
                    Artist = x.Artist,
                    Title = x.Title,
                })
                .Reverse()
                .ToArray();

            var progressId = Guid.NewGuid();

#pragma warning disable 4014
            RunImport(progressId, trackToImport, yaPlayListId, sessionId, UserId);
#pragma warning restore 4014

            var cnt = 0;
            while (progressBar.FindProgressModel(progressId) == null && cnt < 300)
            {
                await Task.Delay(100).ConfigureAwait(true);
                ++cnt;
            }

            return View("ImportProgress", new ProgressWithUrlModel
            {
                Progress = progressBar.FindProgressModel(progressId) ??
                           new ProgressModel {Id = progressId, Processed = 0, Total = 0, SessionId = sessionId},

MuserUI/Views/SyncWizard/ImportProgress.cshtml
@model Tolltech.MuserUI.Models.SyncWizard.ProgressWithUrlModel

@{
    ViewBag.Title = "TollMuser.Импорт";
    Layout = "_Layout";
}

<div id="errorDiv" style="display: none">
    <label style="color: red">Что-то пошло не так</label>
</div>
<div id="playListLinkDiv" style="display: none">
    <a href="@Model.YandexPlaylistUrl">Проверить плейлист</a>
    <div>
        <a href="@Url.Action("ReImport", new {sessionId = Model.SessionId})">
            <input id="toReimportButton" type="button" value="Доимпортировать" class="btn btn-outline-dark"/>
        </a>
    </div>
</div>

<div id="importProgressDiv">
    @await Html.PartialAsync("ImportProgressPartial", Model.Progress)
</div>

<form asp-action="GetImportProgress" asp-controller="SyncWizard"
      data-ajax="true"
      data-ajax-method="GET"
      data-ajax-mode="replace"
      data-ajax-update="#importProgressDiv"
      data-ajax-success="ProgressIteration()"
      data-ajax-failure="ProgressFail()"
      id="getProgressForm">

    <input type="hidden" value="@Model.Progress.Id" name="progressId"/>
</form>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $('#getProgressForm').submit();
        });

        function ProgressIteration() {
            $('#errorDiv').hide();
            var importLogsSaved = $('#importLogsSavedInput').val();
            if (importLogsSaved > 0) {
                $('#playListLinkDiv').show();
                $('#toReimportButton').click();
            } else {
                setTimeout(() => $('#getProgressForm').submit(), 100);
            }
        };

        function ProgressFail() {
            $('#errorDiv').show();
            $('#getProgressForm').submit();
        };
    </script>
}

MuserUI/Views/SyncWizard/ImportProgressPartial.cshtml
@model Tolltech.MuserUI.Models.Sync.ProgressModel

<div class="common">
    <span>
        <label>Импортировано </label>
        <label>@Model.Processed</label>
        <label>/</label>
        <label>@Model.Total</label>
    </span>
    <input type="hidden" value="@(Model.ImportLogsSaved ? 1 : 0)" id="importLogsSavedInput">
</div>

@if (Model.Errors.Count > 0)
{
    <div class="common">
        <label style="color: red">Не удалось импортировать</label>
    </div>

    <select multiple class="track-list">
        @foreach (var error in Model.Errors)
        {
            <option selected value="@error.Message">@error.Track?.Artist - @error.Track?.Title</option>
        }
    </select>
}

MuserUI/Views/SyncWizard/Index.cshtml
@using Tolltech.MuserUI.Models.Sync
@{
    ViewBag.Title = "TollMuser.Загрузка треков";
}

@model InputTracksModel
<div class="common">
    <form id="tracksInputForm" asp-action="GetInputTracks" asp-controller="SyncWizard" method="post">
        <div>
            @Html.TextAreaFor(x => x.Text, new {id = "inputAudioStr", style = "width:100%"})
        </div>
        <span>
            <input type="submit" value="Распарсить треки" class="btn btn-outline-dark"/>
            <label title="Загрузите плейлист вида
Артист1 - Песня1
Артист2 - Песня2">[?]</label>
        </span>
    </form>
</div>
<div class="common">
    <label style="font-size: 30px;">или</label>
</div>
<div class="common">
    <a href="https://chrome.google.com/webstore/detail/tollmuser/enfnbgckehleomocfbehndiiabgapllc?hl=ru">
        <input type="button" value="Поставьте расширение для Chrome" class="btn btn-outline-dark" />
    </a>
</div>
<div class="common">
    <label style="font-size: 30px;">или</label>
</div>
<div class="common">
    <form asp-action="GetInputTracksFromFile" asp-controller="SyncWizard" method="post" enctype="multipart/form-data">
        <input type="file" name="uploadedFile" />
        <input type="submit" value="Загрузить из файла" class="btn btn-outline-dark" />
    </form>
</div>

MuserUI/Views/SyncWizard/InputTracks.cshtml
@using Tolltech.MuserUI.Models.Sync
@{
    ViewBag.Title = "TollMuser.Загрузка треков";
}

@model TracksWizardModel

<div class="common">
    <form method="post" asp-controller="SyncWizard" asp-action="SaveTracks" id="saveSessionForm">
        <div id="inputTracksDiv">
            @Html.ListBox("tracks", Model.Tracks.Select(x => new SelectListItem {Text = x.Artist + " - " + x.Title, Value = Json.Serialize(x).ToString()}), new {@class = "track-list"})
        </div>
        <input id="sessionInputHidden" type="hidden" name="tracksJson"/>
        <input id="saveSessionButton" type="button" value="Перейти к импорту" class="btn btn-outline-dark"/>
    </form>
</div>

@section Scripts{
    <script type="text/javascript">

        function GetTrackForm() {
            var selectedTracks = $("#inputTracksDiv").find('select').find(':selected');
            if (selectedTracks.length == 0) {
                selectedTracks = $("#inputTracksDiv").find('select').find('option');
            }

            var tracks = [];
            for (var i = 0; i < selectedTracks.length; ++i) {
                var data = $(selectedTracks[i]).attr('value');
                tracks.push(JSON.parse(data));
            }

            return {
                Tracks: tracks
            };
        }

        $(document).ready(function() {
            $('#saveSessionButton').click(function() {
                    var form = GetTrackForm();
                    $('#sessionInputHidden').val(JSON.stringify(form));
                    $('#saveSessionForm').submit();
                }
            );
        });


    </script>
}

MuserUI/Views/SyncWizard/LinkToPlaylist.cshtml
@model string

<a href="@Model">Проверить плейлист</a>

MuserUI/Views/SyncWizard/ReImport.cshtml
@{
    ViewBag.Title = "TollMuser.Ошибки импорта";
}

@model Tolltech.MuserUI.Models.SyncWizard.ReImportModel

<div class="common">
    <span>
        <label>Импортировано </label>
        <label>@Model.Success</label>
        <label>/</label>
        <label>@Model.Total</label>
    </span>
</div>

<div id="linkToPlaylistDiv">
    @await Html.PartialAsync("LinkToPlaylist", Model.PlaylistUrl)
</div>

<form id="reImportForm" asp-action="ReImport" asp-controller="SyncWizard" method="post">
    <fieldset>
        <legend>Можно импортировать оставшиеся треки, если соответствие верное</legend>
        <table class="even-odd table-padding" id="reImportTrackTable">
            <tr>
                <td>Искали</td>
                <td>Нашли</td>
            </tr>
            @for (var i = 0; i < Model.Tracks.Length; i++)
            {
                <tr>
                    <td>
                        <label>@Model.Tracks[i].InputArtist - @Model.Tracks[i].InputTitle</label>
                    </td>
                    <td>
                        @if (Model.Tracks[i].Disabled)
                        {
                            <input type="checkbox" disabled="disabled" name="@("reimportTrackCheckbox" + i)">
                        }
                        else
                        {
                            <input type="checkbox" name="@("reimportTrackCheckbox" + i)"
                                   trackid="@Model.Tracks[i].TrackId"
                                   albumid="@Model.Tracks[i].AlbumId"
                                   dbid="@Model.Tracks[i].Id">
                        }
                        <label for="@("reimportTrackCheckbox" + i)">@Model.Tracks[i].Artist - @Model.Tracks[i].Title</label>
                    </td>
                </tr>
            }
        </table>
        <input type="hidden" name="sessionid" value="@Model.SessionId"/>
        <input type="hidden" name="playlistid" value="@Model.PlaylistId"/>
        <input type="hidden" id="reImportInputHidden" name="reImportForm"/>
        <input id="reimportButton" type="button" value="Импортировать" class="btn btn-outline-dark"/>
    </fieldset>
</form>

@section Scripts
{
    <script type="text/javascript">

        function GetReImportTrackForm() {
            var selectedTracks = $('#reImportTrackTable input:checked');

            var tracks = [];
            for (var i = 0; i < selectedTracks.length; ++i) {
                var data = {
                    TrackId: $(selectedTracks[i]).attr('trackid'),
                    AlbumId: $(selectedTracks[i]).attr('albumid'),
                    Id: $(selectedTracks[i]).attr('dbid')
                };
                tracks.push(data);
            }

            return {
                Tracks: tracks,
                PlaylistId: $('#reImportForm input[name=playlistid]').val(),
                SessionId: $('#reImportForm input[name=sessionid]').val()
            };
        }

        $(document).ready(function() {
            $('#reimportButton').click(function() {
                    var form = GetReImportTrackForm();
                    $('#reImportInputHidden').val(JSON.stringify(form));
                    $('#reImportForm').submit();
                }
            );
        });


    </script>
}

MuserUI/Views/SyncWizard/YaPlaylists.cshtml
@model Tolltech.MuserUI.Models.SyncWizard.YaPlaylistsForm
@{
    ViewBag.Title = "TollMuser.Выбор плейлиста";
}

<form id="yaPlaylistForm" asp-action="ImportTracks" asp-controller="SyncWizard" method="post">
    <fieldset>
        <legend>Выберите плейлист</legend>
        @Html.DropDownListFor(x => x.SelectedPlaylistId, Model.Playlists.Select(x => new SelectListItem {Value = x.Id, Text = x.Title, Selected = x.Id == Model.SelectedPlaylistId}), new {id = "yaPlaylists"})
        @Html.Hidden("sessionId", Context.Request.Query["sessionId"])
        @Html.HiddenFor(x => x.Login)
        <input type="submit" value="Импортировать" class="btn btn-outline-dark"/>
    </fieldset>
</form>

MuserUI/Views/SyncWizard/YandexAuthorize.cshtml
@model Tolltech.MuserUI.Models.SyncWizard.YandexAuthorizeForm

@{
    ViewBag.Title = "TollMuser.Авторизация яндекс";
}

<form asp-action="YandexAuthorize" asp-controller="SyncWizard"
      method="post">

    <fieldset>
        <legend>Авторизация Яндекс</legend>
        <div>
            @Html.LabelFor(m => m.Login,"Логин")
            @Html.TextBoxFor(m => m.Login)
        </div>
        <div>
            @Html.LabelFor(m => m.Pass,"Пароль")
            @Html.PasswordFor(m => m.Pass)
        </div>
        @if(Model.Forbid) {
            <div>
                <label style="color: red">Превышено число попыток, попробуйте позже</label>
            </div>
        }
        @if(Model.AuthFailed) {
        <div>
            <label style="color: red">Неверные логин или пароль</label>
        </div>
        }

        @Html.Hidden("sessionId",Context.Request.Query["sessionId"])
        <input type="submit" value="Авторизовать" class="btn btn-outline-dark" />
    </fieldset>
</form>